### ISSUE TITLE
Docs folder and config file in root of project

### ISSUE THREAD

**Issue by weitzman** [nireneko/ddev-mkdocs#1]
Thanks for making this. I'd like to recommend it in https://github.com/ddev/ddev-drupal-contrib. But the [drupal.org Gitlab CI implementation of mkdocs-material ](https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.main.yml?ref_type=heads#L347-362)expects doc files to be in /docs dir, not mkdocs/docs. And it expects mkdocs.yml to be in project root. Would it be possible to make these changes?

**Comment by nireneko** [comment]
Thanks @weitzman, I didn't know that.

Let's wait to the PR of @bhanu951 :)
