### ISSUE TITLE
If this is not maintained, please remove the "ddev-get" topic from the repo

### ISSUE THREAD

**Issue by rfay** [nireneko/ddev-mkdocs#7]
Hi - It looks like this may not be maintained.

If it's not intended to be discoverable by the public, could you please remove the "ddev-get" topic from the repository?

Thanks,
-Randy Fay
DDEV Maintainer

**Comment by nireneko** [comment]
@rfay done, sorry for the inconvenience..

**Comment by rfay** [comment]
Thanks!
